[workspace]
members = [
    "hartex-bitflags-utils",
    "hartex-discord-utils",
    "hartex-errors",
    "hartex-kafka-utils",
    "hartex-log",
    "hartex-macro-utils",
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
