# enable unstable features
unstable_features = true
version = "Two"

brace_style = "PreferSameLine"
color = "Always"
control_brace_style = "ClosingNextLine"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
imports_granularity = "Crate"
struct_lit_single_line = false
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true