# enable unstable features
unstable_features = true
version = "Two"

array_width = 0
brace_style = "PreferSameLine"
color = "Always"
control_brace_style = "ClosingNextLine"
group_imports = "StdExternalCrate"
ignore = [
    "hartex_core/src/discord.rs"
]
imports_layout = "Vertical"
imports_granularity = "Crate"
struct_lit_single_line = false
struct_lit_width = 0
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true