[package]
name = "hartex_discord_worker"
version = "0.1.0"
edition = "2021"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-runtime", "async-signal", "discord-model", "environment", "logging-facilities"] }
hartex_discord_eyre = { path = "../hartex-discord-eyre" }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }

futures-util = "0.3.25"
lapin = "2.1.1"
serde = "1.0.149"
serde_json = "1.0.89"
serde_scan = "0.4.1"
tracing = { version = "0.1.37", features = ["log-always" ] }

[features]
