[package]
name = "hartexbuild_hartexfile"
version = "0.3.0"
edition = "2021"
description = """
HarTexfile specification for HarTex buildsystem
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_errors = { path = "../../rust-utilities/hartex-errors" }

miette = "5.10.0"
serde = { version = "1.0.185", features = ["derive"] }
hcl-rs = "0.16.3"

[features]
