[package]
name = "hartex_discord_configuration_provider"
version = "0.13.0"
edition = "2021"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.83.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_database_queries = { path = "../../database/hartex-database-queries" }

hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

miette = "7.2.0"
tokio-postgres = "0.7.12"

[features]
