[package]
name = "loadbal"
version = "0.1.0"
edition = "2021"
description = """
Load balancer implementation.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["cmdline", "logging", "panicking"] }
env = { path = "../env" }

dashmap = "5.4.0"
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["client", "http1"], default-features = false }
log = "0.4.17"
serde = { version = "1.0.147", features = ["derive", "std"], default-features = false }
serde_json = "1.0.88"
tide = "0.17.0-beta.1"
tokio = { version = "1.21.2", features = ["macros", "net", "rt", "rt-multi-thread", "sync"] }

[build-dependencies]
toml_edit = "0.15.0"

[[bin]]
name = "loadbal"
path = "bin/main.rs"

[lib]
name = "loadbal"
crate-type = ["rlib"]
path = "lib/lib.rs"
