[package]
name = "hartex_localization_macros"
version = "0.1.0"
edition = "2021"
description = """
Localization macros infrastructure for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.54"
quote = "1.0.26"
syn = "2.0.12"

[lib]
name = "hartex_localization_macros"
proc-macro = true
