[package]
name = "hartex_backend_routes_v1"
version = "0.1.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_ratelimiter = { path = "../hartex-backend-ratelimiter" }
hartex_backend_status_util = { path = "../hartex-backend-status-util" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

chrono = { version = "0.4.24", features = ["clock"], default-features = false }
governor = { git = "https://github.com/antifuchs/governor.git" }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master", features = ["json"] }
scylla = "0.8.0"
serde = "1.0.159"
serde_json = "1.0.95"

[features]
