[package]
name = "hartex_bors_database"
version = "0.3.0"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }

chrono = { version = "0.4.26", features = ["clock"], default-features = false }
miette = "5.10.0"
octocrab = { git = "https://github.com/TeamHarTex/octocrab.git" }
sea-orm = { version = "0.12.1", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
sea-orm-migration = { version = "0.12.1", features = ["runtime-tokio-native-tls", "sqlx-sqlite"] }
serde = { version = "1.0.177", features = ["derive"] }
sqlx = { version = "0.7.0", features = ["runtime-tokio-native-tls", "sqlite"] }

[features]
