[workspace]
members = [
    "hartex-backend-driver",
    "hartex-backend-layers",
    "hartex-backend-models",
    "hartex-backend-routes",
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
