version: '3.7'
services:
  proxy:
    image: twilightrs/http-proxy:metrics
    container_name: proxy-1
    environment:
      DISCORD_TOKEN: "irrelevant"
    ports:
      - "3000:80"
  redis:
    image: redis/redis-stack:latest
    container_name: redis-1
    environment:
      REDIS_ARGS: "--requirepass ${DOCKER_REDIS_REQUIREPASS} --loglevel warning"
    ports:
      - "6379:6379"
      - "8001:8001"
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --set redpanda.empty_seed_starts_cluster=false
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
      - --advertise-rpc-addr redpanda-1:33145
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"
      - "28082:28082"
      - "29092:29092"
