[package]
name = "hartex_localization_test"
version = "0.1.0"
edition = "2021"
description = """
Test suite for localizations.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_core = { path = "../hartex-localization-core" }

[dev-dependencies]
hartex_localization_core = { path = "../hartex-localization-core" }
hartex_localization_macros = { path = "../hartex-localization-macros" }

macrotest = { git = "https://github.com/TeamHarTex/macrotest.git", branch = "master" }
rustversion = "1.0.11"
trybuild = "1.0.78"
