[package]
name = "hartex_discord_eyre"
version = "0.1.0"
edition = "2021"
description = """
Eyre implementation tailored for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.67"
eyre = "0.6.8"

[features]
