[package]
name = "hartex_bors_permissions"
version = "0.5.1"
edition = "2021"
description = """
HarTex bors permission resolver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }
hartex_backend_models_v2 = { path = "../../api-backend/hartex-backend-models-v2" }

hartex_bors_core = { path = "../hartex-bors-core" }

hartex_log = { path = "../../rust-utilities/hartex-log" }

http-body = "1.0.0"
hyper = { version = "1.0.1", features = ["client", "http2"] }
hyper-util = { version = "0.1.1", features = ["client-legacy", "http2", "tokio"] }
miette = "5.10.0"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["sync"] }

[features]
