[package]
name = "hartex_backend_models_v1"
version = "0.1.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.170", features = ["derive"] }
sqlx = { version = "0.7.0", features = ["chrono", "runtime-tokio-native-tls"] }

[features]
