[package]
name = "hartex_discord_internal_events"
version = "0.12.0"
edition = "2021"
description = """
Internal event payloads for the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
