[package]
name = "hartex_discord_commands_macros"
version = "0.1.0"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-only"
rust-version = "1.68.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_macro_utils = { path = "../../rust-utilities/hartex-macro-utils" }

proc-macro2 = "1.0.49"
quote = "1.0.23"
syn = { version = "1.0.107", features = ["extra-traits", "full"] }

[features]

[lib]
name = "hartex_discord_commands_macros"
proc-macro = true
