[package]
name = "hartex_backend_models"
version = "0.12.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-or-later"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_configuration_models = { path = "../../discord-frontend/hartex-discord-configuration-models" }

axum = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }

[features]
