[package]
name = "hartex_discord_configuration_manifest"
version = "0.3.0"
edition = "2021"
description = """
The configuration manifest structure of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hcl-rs = "0.16.3"
miette = "5.10.0"
serde = { version = "1.0.185", features = ["derive"] }

[features]
